services:
  - type: web
    name: my-web-service
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn blog.wsgi:application
    runtime: python3
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
